// Code generated by gen/generate-prefixes.mjs from knowledge-base dir-graph.yaml. DO NOT EDIT.
//
// AIFIRST: committed read-only copy of the E5 commit-prefix declaration (CR-2026-049 TASK-08).
// Source: knowledge-base@c98aec6564a6dfe0d993802edfd75884ac1bfab3 dir-graph.yaml
// Consistency is guarded by the gen script --check mode: regenerate != this file -> non-zero exit.
package commitprefix

// generatedConfigRev returns the commit that last changed dir-graph.yaml.
var generatedConfigRev = "c98aec6564a6dfe0d993802edfd75884ac1bfab3"

var generatedPrefixes = map[string]RepoPrefixDecl{
	"ai-first-platform-docs": {
		ID:           "ai-first-platform-docs",
		CanonicalURL: "https://github.com/OldBoy405/AI-First-Platform.git",
		Owner:        "OldBoy405",
		Repo:         "AI-First-Platform",
		Trunk:        "master",
		Prefixes:     []string{"[cr] ", "register ", "archive ", "writeback ", "merge ", "Merge ", "feat(", "fix(", "docs(", "chore(", "test(", "refactor(", "perf("},
	},
	"multica": {
		ID:           "multica",
		CanonicalURL: "https://github.com/OldBoy405/AI-First-multica.git",
		Owner:        "OldBoy405",
		Repo:         "AI-First-multica",
		Trunk:        "main",
		Prefixes:     []string{"MUL-", "Merge ", "merge ", "feat(", "fix(", "docs(", "chore(", "test(", "refactor(", "perf(", "build(", "ci(", "style(", "revert:", "[cr] "},
	},
	"tools": {
		ID:           "tools",
		CanonicalURL: "https://github.com/OldBoy405/AI-First-tools.git",
		Owner:        "OldBoy405",
		Repo:         "AI-First-tools",
		Trunk:        "main",
		Prefixes:     []string{"[cr] ", "Merge ", "merge ", "feat(", "feat:", "fix(", "fix:", "docs(", "docs:", "chore(", "chore:", "test(", "test:", "refactor(", "perf("},
	},
}

