// Code generated by gen/generate-gate-nodes.mjs from tools pipeline-templates/*.pipeline.json. DO NOT EDIT.
//
// AIFIRST: read-only copy of the governance-relevant pipeline node UUIDs (CR-2026-011 TASK-02).
// Source: tools@b6889ff9f5db46a0a8749d971ea31eca03037496 pipeline-templates/{requirement-authoring,architecture-design,code-implementation}.pipeline.json
// Consistency is guarded by the gen script --check mode: regenerate != this file -> non-zero exit.
package governance

// PipelineIDs enumerates the four CR-scoped pipeline templates (in dependency order).
var PipelineIDs = struct {
	RequirementAuthoring string
	ArchitectureDesign   string
	CodeImplementation   string
	FeatureWriteback     string
}{
	RequirementAuthoring: "requirement-authoring",
	ArchitectureDesign:   "architecture-design",
	CodeImplementation:   "code-implementation",
	FeatureWriteback:     "feature-writeback",
}

// GateNode identifies one governance-relevant node in a pipeline template by
// its stable node UUID. The UUID is a template-authored constant (every node
// in every *.pipeline.json carries a fixed id) — this is the single decision
// point for node identity (SDD TASK-02/TSUG-002): both the projector here and
// any future Runner (CR-H) read the same generated constants, so the same
// logical node can never be projected under two different node_id values.
type GateNode struct {
	PipelineID string
	NodeID     string // UUID string form; stored verbatim into pipeline_node_run.node_id
	Seq        int    // 1-indexed position in the template's nodes[] array
	Kind       string // matches pipeline_node_run.kind
}

// ApprovalGateNodes maps a gates.json#approvalStages key (requirement/tech-design/
// dev-start/code) to its human_approval node.
var ApprovalGateNodes = map[string]GateNode{
	"requirement": {PipelineID: "requirement-authoring", NodeID: "00000000-0000-0000-0011-000000000005", Seq: 5, Kind: "human_approval"},
	"tech-design": {PipelineID: "architecture-design", NodeID: "00000000-0000-0000-0014-000000000003", Seq: 3, Kind: "human_approval"},
	"dev-start":   {PipelineID: "code-implementation", NodeID: "00000000-0000-0000-0015-000000000004", Seq: 4, Kind: "human_approval"},
	"code":        {PipelineID: "code-implementation", NodeID: "00000000-0000-0000-0015-000000000010", Seq: 10, Kind: "human_approval"},
}

// ReviewGateNodes maps a review-event stage key (TASK-03's three scanned
// stages: requirement/tech-design/code — dev-start has no preceding AI review)
// to the review skill node whose blocked/passed outcome the review event
// channel projects.
var ReviewGateNodes = map[string]GateNode{
	"requirement": {PipelineID: "requirement-authoring", NodeID: "00000000-0000-0000-0011-000000000004", Seq: 4, Kind: "skill"},
	"tech-design": {PipelineID: "architecture-design", NodeID: "00000000-0000-0000-0014-000000000002", Seq: 2, Kind: "skill"},
	"code":        {PipelineID: "code-implementation", NodeID: "00000000-0000-0000-0015-000000000009", Seq: 9, Kind: "skill"},
}
