// Code generated by gen/generate-transitions.mjs from tools dir-graph.yaml. DO NOT EDIT.
//
// AIFIRST: read-only copy of the CR state machine (CR-2026-002 TASK-04).
// Source: tools@7a7479819854362db5fd03cb8d1eae48aaa65a3c dir-graph.yaml#change-request-track.state_machine
// 28 declared transitions (incl. wildcards), 50 after expansion.
// Consistency is guarded by the gen script --check mode: regenerate != this file -> non-zero exit.
package governance

// Transition is one legal state-machine transition. An empty From means pre-registration ((new)).
type Transition struct {
	From    string
	To      string
	Trigger string
}

// Transitions follows the dir-graph.yaml declaration order (wildcards expanded).
var Transitions = []Transition{
	{From: "", To: "drafting", Trigger: "requirement-register"},
	{From: "drafting", To: "requirement-reviewing", Trigger: "review-requirement"},
	{From: "requirement-reviewing", To: "requirement-reviewing", Trigger: "review-requirement"},
	{From: "drafting", To: "drafting", Trigger: "review-requirement:block -> write-requirement-prd"},
	{From: "requirement-reviewing", To: "requirement-approved", Trigger: "approve-requirement"},
	{From: "requirement-reviewing", To: "drafting", Trigger: "approve-requirement:reject -> write-requirement-prd"},
	{From: "requirement-approved", To: "tech-designing", Trigger: "write-tech-design"},
	{From: "tech-designing", To: "tech-design-review-pending", Trigger: "write-tech-design-complete"},
	{From: "tech-design-review-pending", To: "tech-designing", Trigger: "review-tech-design:block -> write-tech-design"},
	{From: "tech-design-review-pending", To: "tech-designing", Trigger: "approve-tech-design:reject -> write-tech-design"},
	{From: "tech-design-review-pending", To: "tech-design-reviewed", Trigger: "approve-tech-design"},
	{From: "tech-design-reviewed", To: "task-breakdown", Trigger: "write-dev-tasks"},
	{From: "task-breakdown", To: "task-breakdown", Trigger: "write-dev-tasks"},
	{From: "task-breakdown", To: "tech-design-reviewed", Trigger: "approve-dev-start:reject -> write-dev-plan"},
	{From: "task-breakdown", To: "tech-design-reviewed", Trigger: "review-dev-plan:block -> write-dev-plan"},
	{From: "task-breakdown", To: "tech-design-review-pending", Trigger: "review-dev-plan:upstream-design-blocker"},
	{From: "task-breakdown", To: "developing", Trigger: "approve-dev-start"},
	{From: "developing", To: "developing", Trigger: "write-test-report:block -> implement-code"},
	{From: "developing", To: "developing", Trigger: "review-code:block -> implement-code"},
	{From: "developing", To: "code-reviewing", Trigger: "review-code"},
	{From: "code-reviewing", To: "developing", Trigger: "approve-code:reject -> implement-code"},
	{From: "code-reviewing", To: "code-approved", Trigger: "approve-code"},
	{From: "code-approved", To: "merging", Trigger: "merge-feature-branch"},
	{From: "code-approved", To: "developing", Trigger: "merge-feature-branch:release-drift -> implement-code"},
	{From: "merging", To: "writing-back", Trigger: "writeback-prd-sdd"},
	{From: "writing-back", To: "archived", Trigger: "cr-archive"},
	{From: "drafting", To: "rejected", Trigger: "cr-review-record:reject"},
	{From: "requirement-reviewing", To: "rejected", Trigger: "cr-review-record:reject"},
	{From: "requirement-approved", To: "rejected", Trigger: "cr-review-record:reject"},
	{From: "tech-designing", To: "rejected", Trigger: "cr-review-record:reject"},
	{From: "tech-design-review-pending", To: "rejected", Trigger: "cr-review-record:reject"},
	{From: "tech-design-reviewed", To: "rejected", Trigger: "cr-review-record:reject"},
	{From: "task-breakdown", To: "rejected", Trigger: "cr-review-record:reject"},
	{From: "developing", To: "rejected", Trigger: "cr-review-record:reject"},
	{From: "code-reviewing", To: "rejected", Trigger: "cr-review-record:reject"},
	{From: "code-approved", To: "rejected", Trigger: "cr-review-record:reject"},
	{From: "merging", To: "rejected", Trigger: "cr-review-record:reject"},
	{From: "writing-back", To: "rejected", Trigger: "cr-review-record:reject"},
	{From: "drafting", To: "withdrawn", Trigger: "cr-review-record:withdraw"},
	{From: "requirement-reviewing", To: "withdrawn", Trigger: "cr-review-record:withdraw"},
	{From: "requirement-approved", To: "withdrawn", Trigger: "cr-review-record:withdraw"},
	{From: "tech-designing", To: "withdrawn", Trigger: "cr-review-record:withdraw"},
	{From: "tech-design-review-pending", To: "withdrawn", Trigger: "cr-review-record:withdraw"},
	{From: "tech-design-reviewed", To: "withdrawn", Trigger: "cr-review-record:withdraw"},
	{From: "task-breakdown", To: "withdrawn", Trigger: "cr-review-record:withdraw"},
	{From: "developing", To: "withdrawn", Trigger: "cr-review-record:withdraw"},
	{From: "code-reviewing", To: "withdrawn", Trigger: "cr-review-record:withdraw"},
	{From: "code-approved", To: "withdrawn", Trigger: "cr-review-record:withdraw"},
	{From: "merging", To: "withdrawn", Trigger: "cr-review-record:withdraw"},
	{From: "writing-back", To: "withdrawn", Trigger: "cr-review-record:withdraw"},
}

// TerminalStatuses is the set of terminal states: no transitions are accepted once entered.
var TerminalStatuses = map[string]bool{"archived": true, "rejected": true, "withdrawn": true}

// KnownStatuses enumerates every named status (the (new) empty string is excluded).
var KnownStatuses = map[string]bool{
	"archived":                   true,
	"code-approved":              true,
	"code-reviewing":             true,
	"developing":                 true,
	"drafting":                   true,
	"merging":                    true,
	"rejected":                   true,
	"requirement-approved":       true,
	"requirement-reviewing":      true,
	"task-breakdown":             true,
	"tech-design-review-pending": true,
	"tech-design-reviewed":       true,
	"tech-designing":             true,
	"withdrawn":                  true,
	"writing-back":               true,
}

// IsLegalTransition reports whether (from -> to) is a declared legal transition.
// An empty trigger matches on (from, to) only (the commit-scan fallback channel
// cannot recover the trigger).
func IsLegalTransition(from, to, trigger string) bool {
	for _, t := range Transitions {
		if t.From != from || t.To != to {
			continue
		}
		if trigger == "" || t.Trigger == trigger {
			return true
		}
	}
	return false
}
