// Code generated by gen/generate-config.mjs from knowledge-base maturity-config.yaml. DO NOT EDIT.
//
// AIFIRST: committed read-only copy of the maturity config declaration (CR-2026-047 TASK-01).
// Source: knowledge-base@bcd42b41f1dd5261f21439b066417fe9e99f0cb6 maturity-config.yaml
// Consistency is guarded by the gen script --check mode: regenerate != this file -> non-zero exit.
package maturity

// GeneratedConfigRev returns the source repo HEAD SHA recorded at generation time.
func GeneratedConfigRev() string { return "bcd42b41f1dd5261f21439b066417fe9e99f0cb6" }

// GeneratedConfig returns the committed copy of maturity-config.yaml.
func GeneratedConfig() ConfigV1 {
	return ConfigV1{
		Schema:            "ai-first.maturity-config/v1",
		ObservationWeeks:  4,
		CalibrationStatus: "observing",
		Dimensions: map[DimensionKey][]MetricKey{
			DimAIF: {MetricTokenIntensity, MetricAIPenetration},
			DimSII: {MetricCRThroughputPerCapita},
			DimOFI: {MetricProjectCollabScale, MetricProjectActiveRate},
			DimEPC: {MetricPrototypeDirectRate},
			DimACM: {MetricTeamAgentDepth, MetricProcessCompletionRate},
		},
		Metrics: map[MetricKey]MetricConfig{
			MetricTokenIntensity:        {Weight: 0.125, Floor: 0, Target: 1},
			MetricAIPenetration:         {Weight: 0.125, Floor: 0, Target: 1},
			MetricCRThroughputPerCapita: {Weight: 0.125, Floor: 0, Target: 1},
			MetricProjectCollabScale:    {Weight: 0.125, Floor: 0, Target: 1},
			MetricProjectActiveRate:     {Weight: 0.125, Floor: 0, Target: 1},
			MetricPrototypeDirectRate:   {Weight: 0.125, Floor: 0, Target: 1},
			MetricTeamAgentDepth:        {Weight: 0.125, Floor: 0, Target: 1},
			MetricProcessCompletionRate: {Weight: 0.125, Floor: 0, Target: 1},
		},
	}
}

// GeneratedPriceMap returns the committed copy of the optional model-prices.yaml.
// The bool is false when no price map is declared.
func GeneratedPriceMap() (PriceMap, bool) { return PriceMap{}, false }
